name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Check out source code
        uses: actions/checkout@master

      - name: Build
        env:
          GO111MODULE: "on"
        run: go build .

      - name: Test
        run: go test -race ./...
