name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out source code
        uses: actions/checkout@master

      - name: Build
        env:
          GO111MODULE: "on"
        run: go build .

      - name: Test
        run: go test -race ./... -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v1
